# Generated by Django 2.0.7 on 2018-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thoughts',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='categories',
            name='has_childs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thoughts',
            name='first_letter',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
    ]
