# Generated by Django 2.0.7 on 2018-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_auto_20180718_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
