# Generated by Django 4.1.6 on 2023-02-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0003_auto_20180803_1600"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Thoughts",
            new_name="Thought",
        ),
    ]
