# Generated by Django 4.1.6 on 2023-02-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0004_rename_categories_category_rename_thoughts_thought"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="has_childs",
        ),
    ]
